Home task3
apavlenkoMN/apavlenko_Sum22Automation pull request #2
Opened 2022-06-08 11:17 UTC by apavlenkoMN

4 items - 4 different class

2022-06-08 13:22 UTC, mkarpenkoProvectus requested changes
нужно ещё раз глянуть на задание с абсолютными величинами чисел, добавить определение этого самого абсолютного значения (модуля) при сравнении

2022-06-08 13:22 UTC, mkarpenkoProvectus commented on java_core_lessons/src/session3/Magnitude_HT3.java
> +        if (number1 > number2 ){
здесь мы сравниваем просто значения чисел, т.е. 1 будет больше -2
но по условию задачи нужно сравнивать именно абсолютные значения чисел, и тогда абсолютное значение числа -2 будет больше абсолютного значения числа 1, что и нужно по условию

2022-06-08 20:50 UTC, apavlenkoMN commented on java_core_lessons/src/session3/Magnitude_HT3.java
> +        if (number1 > number2 ){
согласен, мне казалось что я правильно понял задание

возможно я зря сразу при определении преобразую в абсолютное
int number1 = Math.abs(scanner.nextInt());

в данном случае мы теряем оригинально введенные отрицательные числа, могу вынести отдельно

но даже ничего не меняя - работает так
Please enter two numbers: 
-2
1
2 is bigger than 1

2022-06-09 11:10 UTC, mkarpenkoProvectus commented on java_core_lessons/src/session3/Magnitude_HT3.java
> +        if (number1 > number2 ){
пропустил этот момент, что Math.abs вызывается вначале при считывании чисел. немного неочевидно получилось, и да, теряется изначально введенное значение. но в таком случае - результат получается верный

2022-06-09 11:10 UTC, mkarpenkoProvectus approved these changes

2022-06-09 11:10 UTC, merged